USE malison;
create table ROLES(ID int(10) primary key AUTO_INCREMENT, ROLE VARCHAR(100) NOT NULL, USERNAME VARCHAR(100) NOT NULL); 

INSERT INTO ROLES(ID, ROLE, USERNAME) VALUES( 1, 'ADMIN', 'pnyota');